// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34zD-mQOmQrvfChaLLv2jox1c26TWcxI',
    appId: '1:262345006044:web:73aace20909dfadddbcd19',
    messagingSenderId: '262345006044',
    projectId: 'flutter-firebase-dersler-be995',
    authDomain: 'flutter-firebase-dersler-be995.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-be995.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lJgceGTLQUuCl67k3xMZE75Tm-XOrs4',
    appId: '1:262345006044:android:340096024873f4e6dbcd19',
    messagingSenderId: '262345006044',
    projectId: 'flutter-firebase-dersler-be995',
    storageBucket: 'flutter-firebase-dersler-be995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaVexnVWAZKILM1e05jHplj1ZabydalY',
    appId: '1:262345006044:ios:65fef9af90b34431dbcd19',
    messagingSenderId: '262345006044',
    projectId: 'flutter-firebase-dersler-be995',
    storageBucket: 'flutter-firebase-dersler-be995.appspot.com',
    iosClientId: '262345006044-s080gfrj7istrv245lke59bj924lr451.apps.googleusercontent.com',
    iosBundleId: 'firebasekullanim.flutterFirebaseDersleri',
  );
}
